### ISSUE TITLE
libgnutls not loading libintl.8.dylib since last release

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/gnutls-feedstock#3]
Recent build (version 3.5.19) appears to be broken on OSX.  I am getting:

```
dyld: Library not loaded: @rpath/libintl.8.dylib
  Referenced from: /Users/travis/miniconda/lib/libgnutls.30.dylib
```

**Comment by sdvillal** [comment]
Ups, indeed there is a little hidden "libintl not found" message in the build logs, and everything points to gettext. I'm not a mac man but will try to fix it when I find a minute. Any help is welcome.

In the meantime, can you pin to the previous version?

**Comment by sdvillal** [comment]
So the problem is that I assumed wrongly that gettext had already centralized pinnings, which it does not and therefore it is not added automagically to the runtime dependencies. Also apparently pinning is not trivial:
https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/11

Will hopefully fix in a second.

**Comment by ocefpaf** [comment]
> So the problem is that I assumed wrongly that gettext had already centralized pinnings

Do you want to send a PR to `conda-forge-pinning` with the global pinning?

**Comment by sdvillal** [comment]
Once #5 is merged this will be solved.

@ocefpaf I will send a PR tomorrow with the pin I used here, let's see if it is well received.

**Comment by ocefpaf** [comment]
> let's see if it is well received.

Thanks! It is always well received :smile: 
We may need to figure out the information about the ABI first though to make it efficient.

**Comment by sdvillal** [comment]
The hotfix version has made it to the repos. Once we get a proper conda-forge wide pin, I will trigger a new build.

**Comment by sdvillal** [comment]
@SylvainCorlay thanks for the speedy report, hopefully we have caught this early enough that it has not broken many people envs.

**Comment by SylvainCorlay** [comment]
Thanks! Double checking in my environment.

**Comment by SylvainCorlay** [comment]
It is apparently fixed!

**Comment by SylvainCorlay** [comment]
Many thanks for fixing this so quickly @sdvillal !
